### ISSUE TITLE
possible accidentally left in text in q #5?

### ISSUE THREAD

**Issue by bambery** [math434/social-networks-amy-max-lauren#18]
In exercise 5, there is a header that reads
"## Still need to finish part 1 and 2"

Is that an old note to yourself, @fstcar , or is that indicating there is missing work?

**Comment by bambery** [comment]
After looking at the last PR and thread, I think the note is a current indication of status, so I'll close this

**Comment by fstcar** [comment]
Yes it is the current status of the problem I just included it in the merge since the function is necessary for all other exercises I completed
